### ISSUE TITLE
yarn dev fails on OSX

### ISSUE THREAD

**Issue by vesper8** [Physiix/topsi-project-manager#50]
The installation instructions are extremely minimal and I get this error after running `yarn install` and `yarn dev` on OSX

```
 INFO  Launching Electron...
App threw an error during load
Error: Path not found
    at new DBUtils (webpack:///./src/core/Database.ts?:27:19)
    at new DBManager (webpack:///./src/core/DBManager.ts?:7:22)
    at eval (webpack:///./src/core/DBManager.ts?:56:64)
    at Module../src/core/DBManager.ts (/DEV/_PROJECT_MANAGER/topsi-project-manager/dist_electron/index.js:1225:1)
    at __webpack_require__ (/DEV/_PROJECT_MANAGER/topsi-project-manager/dist_electron/index.js:20:30)
    at eval (webpack:///./src/background.ts?:5:73)
    at Module../src/background.ts (/DEV/_PROJECT_MANAGER/topsi-project-manager/dist_electron/index.js:1201:1)
    at __webpack_require__ (/DEV/_PROJECT_MANAGER/topsi-project-manager/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.ts?:1:18)
    at Object.0 (/DEV/_PROJECT_MANAGER/topsi-project-manager/dist_electron/index.js:1248:1)
```

Would also have liked to know how I can make the app use a local MySQL database, if at all possible.

**Comment by Physiix** [comment]
Hi, I'm in the process of refactoring the code. The master branch is pretty much broken right now. 
I'm also working on a plugin system which would eventually let users implement custom logic. 
You could use MySQL by writing your own plugin then.

**Comment by thunderrous** [comment]
> I'm in the process of refactoring the code. The master branch is pretty much broken right now.
> I'm also working on a plugin system which would eventually let users implement custom logic.
> You could use MySQL by writing your own plugin then.

Hello, is there a planned release date for the working version? This is pretty much closest to what I need of my app.

**Comment by VincenzoLaSpesa** [comment]
Could you create a tag (or a branch) with the last stable release?
